#docker run -it --rm -p 8888:8888 -p 4040:4040 jupyter/pyspark-notebook
#FROM datamechanics/spark:3.2.1-hadoop-3.3.1-java-11-scala-2.12-python-3.8-dm18
FROM jupyter/pyspark-notebook

#User root
USER root   

#update
RUN apt-get update && \
    apt-get install -y curl \
    wget \
    vim \
    mysql-server

RUN systemctl start mysql.service
RUN sudo mysql
RUN ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'matthias';
RUN exit

#pip3 install
RUN pip3 install numpy
RUN pip3 install scipy
RUN pip3 install scikit-learn
RUN pip3 install pandas
RUN pip3 install psycopg2-binary
RUN pip3 install mysql-connector-python

# Make port 8888 available to the world outside this container
RUN mkdir /home/neogiciel
COPY file.csv /home/neogiciel/
COPY mysql-connector-java-5.1.38.jar  /home/neogiciel/
COPY mysql-connector-java-8.0.23.jar  /home/neogiciel/


